version: '3.8'

services:
  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: retrotool
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - retrotool-net
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    ports:
      - "8081:8081"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - retrotool-net

volumes:
  mysql-data:

networks:
  retrotool-net:
