spring:
  datasource:
    url: jdbc:mysql://db:3306/retrotool?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: user
    password: password
    hikari:
      connection-timeout: 30000
      initialization-fail-timeout: -1
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  batch:
    jdbc:
      initialize-schema: never

server:
  port: 8081
